name: Pipeline Demo
on:
  workflow_dispatch:
    inputs:
      query_object:
        description: 'Object Query to retrieve from Secrets Manager SaaS'
        required: true
        default: ''
      encode:
        description: 'Do you want the returned credential object values b64 encoded?'
        requred: false
        default: 'false'

permissions:
  id-token: write
  contents: read

jobs:
  stage-secrets:
    runs-on: [ ubuntu-latest ] # only use self-hosted, this is a poc.
    outputs:
      cyberark_username: ${{ steps.cyberark.outputs.cyberark_username }}
      cyberark_password: ${{ steps.cyberark.outputs.cyberark_password }}
      vars: ${{ steps.cyberark.outputs.vars }}
    steps:
      - name: Stage Secrets
        id: cyberark
        env:
          CONJUR_URL: "https://sme-andrew.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "github"
        run: |
          echo "Retrieving JWT Token from Github"
          GIT_TOKEN=$(curl -s -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

          echo "Authenticating to Conjur"
          SESSION_TOKEN=$(curl -s --request POST "$CONJUR_URL/authn-jwt/$CONJUR_SERVICE_ID/$CONJUR_ACCOUNT/authenticate" --header "Content-Type: application/x-www-form-urlencoded" --header "Accept-Encoding: base64" --data-urlencode "jwt=$GIT_TOKEN")
          
          resources=$(curl -s -H "Authorization:Token token=\"${SESSION_TOKEN}\"" "$CONJUR_URL/resources/$CONJUR_ACCOUNT?kind=variable&search=${{ github.event.inputs.query_object }}" | jq -r '.[].id')

          paths=""
          
          for resource in $resources
          do
              path+="${resource},"
          done
          api_path="${path:0:${#path}-1}"          
          
          variables=$(curl -s -H "Authorization:Token token=\"${SESSION_TOKEN}\"" "$CONJUR_URL/secrets?variable_ids=$api_path")
          username=$(curl -s -H "Authorization:Token token=\"${SESSION_TOKEN}\"" "$CONJUR_URL/secrets/conjur/variable/data/vault/aam_deposits/${{ github.event.inputs.query_object }}/username")
          password=$(curl -s -H "Authorization:Token token=\"${SESSION_TOKEN}\"" "$CONJUR_URL/secrets/conjur/variable/data/vault/aam_deposits/${{ github.event.inputs.query_object }}/password")

          echo "cyberark_username=$username" >> "$GITHUB_OUTPUT"
          echo "cyberark_password=$password" >> "$GITHUB_OUTPUT"
          echo "vars=$variables" >> "$GITHUB_OUTPUT"

  demo:
    runs-on: [ ubuntu-latest ] # only use self-hosted, this is a poc.
    needs: [stage-secrets]
    steps:
      - name: Testing Credentials
        run: |
          echo "username: ${{ needs.stage-secrets.outputs.cyberark_username }}"
          echo "password: ${{ needs.stage-secrets.outputs.cyberark_password }}"
          echo "variables: ${{ needs.stage-secrets.outputs.vars }}"
